# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.cache/wt} [current_project]
set_property parent.project_path {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/imports/EE2026/Lab 5 Project/SoundDisplay/SoundDisplay.srcs/sources_1/new/Audio_Capture.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/imports/EE2026/Lab 5 Project/SoundDisplay/SoundDisplay.srcs/sources_1/new/Oled_Display.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/clk12hz.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/imports/EE2026/Lab 5 Project/SoundDisplay/SoundDisplay.srcs/sources_1/new/clk20k.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/imports/EE2026/Lab 5 Project/safe_seg/safe_seg.srcs/sources_1/new/clk381hz.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/clk4hz.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/imports/EE2026/Lab 5 Project/SoundDisplay/SoundDisplay.srcs/sources_1/new/clk6p25m.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/clk_custom.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/imports/EE2026/Lab 4/Single_pulse_debouncer/Single_pulse_debouncer.srcs/sources_1/new/dflipflop.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/display_freq.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/imports/EE2026/Lab 4/Single_pulse_debouncer/Single_pulse_debouncer.srcs/sources_1/new/flipflop.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/goku_display.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/maxvolume.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/menu.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/menu_goku.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/menu_midi.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/menu_music.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/menu_vol.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/mic_freq.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/midi_display.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/imports/EE2026/Lab 5 Project/SoundDisplay/SoundDisplay.srcs/sources_1/new/multiplexer.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/note_determiner.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/oledvolume.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/pixel_coords.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/segmentdisplay.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/imports/EE2026/Lab 3/blinky/blinky.srcs/sources_1/new/slow_blinky.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/supersaiyan.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/tuner.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/tuner_display.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/new/volumedisplay.v}
  {D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/sources_1/imports/EE2026/Lab 5 Project/SoundDisplay/SoundDisplay.srcs/sources_1/new/Top_Student.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/constrs_1/imports/new/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/NUS/EE2026/finalProject/Project Added menu icons and changed midi.xpr/oledvolume/oledvolume.srcs/constrs_1/imports/new/Basys3_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
